--COR
--VERIFICAÇÃO DE CLASSIFICAÇÃO DIFERENTE DE COR/NCOR
CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_COR_VERIFICA_CLASSIFICACAO_COR"
	(
	"CLASSE_DE_CUSTO"
	,"DESCRICAO_DA_CLASSE_DE_CUSTO"
	,"CONTROLADORIA_COR_NAO_COR"
	,"CONTROLADORIA_NATUREZA"
	,"REGULATORIO_COR_NAO_COR"
	,"REGULATORIO_NATUREZA"
	)
	
	AS
	
	(
	SELECT DISTINCT A.CLASSE_DE_CUSTO
	,A.DESCRICAO_DA_CLASSE_DE_CUSTO
	,A.COR_NAO_COR AS CONTROLADORIA_COR_NAO_COR
	,A.NATUREZA AS CONTROLADORIA_NATUREZA
	,B.COR_NCOR_REGULATORIO AS REGULATORIO_COR_NAO_COR
	,B.NATUREZA_REGULATORIO AS REGULATORIO_NATUREZA
	FROM COR_PMSO A
	LEFT JOIN COR_DEPARA_PLUZ_CONTROLADORIA B ON B.CLASSE_DE_CUSTO_CONTROLADORIA = A.CLASSE_DE_CUSTO
	WHERE (UPPER(A.NATUREZA) != UPPER(B.NATUREZA_REGULATORIO))
		OR (A.COR_NAO_COR != B.COR_NCOR_REGULATORIO)
		OR (B.COR_NCOR_REGULATORIO IS NULL)
	);





--MONTAGEM BASES CONTROLADORIA
CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_COR_BASE_ORCADO_REALIZADO" (
	"EMPRESA"
	,"TIPO"
	,"COR_NAO_COR"
	,"NATUREZA"
	,"ANO"
	,"JANEIRO"
	,"FEVEREIRO"
	,"MARCO"
	,"ABRIL"
	,"MAIO"
	,"JUNHO"
	,"JULHO"
	,"AGOSTO"
	,"SETEMBRO"
	,"OUTUBRO"
	,"NOVEMBRO"
	,"DEZEMBRO"
	,"ACUMULADO"	
	)
	
	AS
	
	(

--VALORES ORÇADOS
	SELECT A.EMPRESA
	,'ORÇADO' AS TIPO
	,A.COR_NAO_COR
	,A.NATUREZA
	,A.ANO AS ANO
	,SUM(A.JAN) AS JANEIRO
	,SUM(A.FEV) AS FEVEREIRO
	,SUM(A.MAR) AS MARCO
	,SUM(A.ABR) AS ABRIL
	,SUM(A.MAI) AS MAIO
	,SUM(A.JUN) AS JUNHO
	,SUM(A.JUL) AS JULHO
	,SUM(A.AGO) AS AGOSTO
	,SUM(A."SET") AS SETEMBRO
	,SUM(A."OUT") AS OUTUBRO
	,SUM(A.NOV) AS NOVEMBRO
	,SUM(A.DEZ) AS DEZEMBRO
	,SUM(A.ACUMULADO) AS ACUMULADO
	FROM COR_PMSO A
	WHERE A.CATEGORIA_ORIGINAL = 'Bottom UP_FM'
	GROUP BY A.EMPRESA
		,A.COR_NAO_COR
		,A.NATUREZA
		,A.ANO

UNION ALL
	
--VALORES REALIZADOS
	SELECT A.EMPRESA
	,'REALIZADO' AS TIPO
	,A.COR_NAO_COR
	,A.NATUREZA
	,A.ANO AS ANO
	,SUM(A.JAN) AS JANEIRO
	,SUM(A.FEV) AS FEVEREIRO
	,SUM(A.MAR) AS MARCO
	,SUM(A.ABR) AS ABRIL
	,SUM(A.MAI) AS MAIO
	,SUM(A.JUN) AS JUNHO
	,SUM(A.JUL) AS JULHO
	,SUM(A.AGO) AS AGOSTO
	,SUM(A."SET") AS SETEMBRO
	,SUM(A."OUT") AS OUTUBRO
	,SUM(A.NOV) AS NOVEMBRO
	,SUM(A.DEZ) AS DEZEMBRO
	,SUM(A.ACUMULADO) AS ACUMULADO
	FROM COR_PMSO A
	WHERE A.CATEGORIA_ORIGINAL = 'Realizado_FM'
	GROUP BY A.EMPRESA
		,A.COR_NAO_COR
		,A.NATUREZA
		,A.ANO
	);

